version: '2'
services:
  carpoolear_frontend:
    build: .
    tty: true
    container_name: carpoolear_frontend
    environment:
      HOST: '0.0.0.0'
    ports:
      - "${APP_PORT:-8081}:8080"
    networks:
      - esnet
    volumes:
      - .:/app
networks:
  esnet:
    driver: bridge
